name: CI

on:
  workflow_dispatch:

jobs:
  main_job:
    name: Main job
    env:
      AZ_CREDS: ${{ secrets.AZ_CREDS }}
      TF_VERSION: 1.3.9
    runs-on: ubuntu-22.04
    environment: production
    defaults:
      run:
        shell: bash
    steps:

      - name: Authenticate to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CREDS }}

      - name: Install kubelogin
        run: |
          sudo apt-get update
          sudo snap install kubelogin

      - name: Checkout
        uses: actions/checkout@v3

      - name: Pre-Terraform setup
        run: ./setup.sh

      - name: Setup Terraform Action
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Set env variables for Terraform Azure authentication
        run: |
          echo "ARM_CLIENT_ID=$(echo $AZ_CREDS | jq -r '.clientId')" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=$(echo $AZ_CREDS | jq -r '.clientSecret')" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=$(echo $AZ_CREDS | jq -r '.subscriptionId')" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=$(echo $AZ_CREDS | jq -r '.tenantId')" >> $GITHUB_ENV

      - name: Check Terraform version
        run: "terraform version"

      - name: terraform format
        run: terraform fmt

      - name: terraform init
        run: terraform init
